import type { DiscoveryReport, BackendReport } from '../types.js';

interface ApiMapBackend {
  url: string;
  endpoints: ApiMapEndpoint[];
}

interface ApiMapEndpoint {
  path: string;
  method: string;
  statusCode: number;
  ok: boolean;
  responseTimeMs: number;
  responseSchema?: string;
}

interface ApiMap {
  _note: string;
  generated_at: string;
  backends: Record<string, ApiMapBackend>;
}

/**
 * Generates the machine-readable api-map.json content from a DiscoveryReport.
 */
export function generateApiMap(report: DiscoveryReport): string {
  const backends: Record<string, ApiMapBackend> = {};

  for (const backend of report.backends) {
    backends[backend.name] = buildBackendEntry(backend);
  }

  const apiMap: ApiMap = {
    _note: 'This file is auto-generated by apps/discovery. Do not edit manually.',
    generated_at: report.generatedAt,
    backends,
  };

  return JSON.stringify(apiMap, null, 2);
}

function buildBackendEntry(backend: BackendReport): ApiMapBackend {
  return {
    url: backend.baseUrl,
    endpoints: backend.endpoints.map((ep) => {
      const entry: ApiMapEndpoint = {
        path: ep.path,
        method: ep.method,
        statusCode: ep.statusCode,
        ok: ep.ok,
        responseTimeMs: ep.responseTimeMs,
      };
      if (ep.responseSchema !== undefined) {
        entry.responseSchema = ep.responseSchema;
      }
      return entry;
    }),
  };
}
